blueprint:
  name: Danfoss Ally (Zigbee2MQTT) - Pause Heating On Open Window
  description: >
    Sets Danfoss Ally thermostats to Window open/close = Open when any selected
    open/close sensor has remained open for the configured time.

    This blueprint targets Zigbee2MQTT by controlling each thermostat's
    `window_open_external` switch entity (turn on = open window detected).
  domain: automation

  input:
    open_close_sensors:
      name: Open/Close sensors
      description: One or more binary sensors that report on/off for open/closed.
      selector:
        entity:
          multiple: true
          filter:
            - domain: binary_sensor
              device_class:
                - door
                - window

    thermostats_window_open:
      name: Danfoss Ally window-open controls
      description: >
        Select 1..n Zigbee2MQTT switch entities for `window_open_external`
        (typically named like `switch.<trv>_window_open_external`).
      selector:
        entity:
          multiple: true
          filter:
            - domain: switch
              integration: mqtt

    open_for:
      name: Open duration before pause
      description: How long a sensor must stay open before heating is paused.
      default: "00:05:00"
      selector:
        duration:

mode: restart
max_exceeded: silent

variables:
  trv_window_open_switches: !input thermostats_window_open

trigger:
  - platform: state
    entity_id: !input open_close_sensors
    from: "off"
    to: "on"
    for: !input open_for

action:
  - repeat:
      for_each: "{{ trv_window_open_switches }}"
      sequence:
        - service: switch.turn_on
          target:
            entity_id: "{{ repeat.item }}"
